# Tox file so we can test ourselves.
[tox]
envlist = py{311,314}
skip_missing_interpreters = True

[gh-actions]
# See https://pypi.org/project/tox-gh-actions/
python =
    3.11: py311
    3.14: py314

[testenv]
skip_install = true
commands = python test.py
